ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS "machineName" TEXT,
  ADD COLUMN IF NOT EXISTS "machineModel" TEXT,
  ADD COLUMN IF NOT EXISTS "machineSerial" TEXT,
  ADD COLUMN IF NOT EXISTS "hasHotel" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "hotelDailyRate" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "transportMode" TEXT,
  ADD COLUMN IF NOT EXISTS "flightAirport" TEXT,
  ADD COLUMN IF NOT EXISTS "flightDepartureAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "flightReturnAt" TIMESTAMP(3);
