ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS "hotelName" TEXT,
  ADD COLUMN IF NOT EXISTS "hotelAddress" TEXT,
  ADD COLUMN IF NOT EXISTS "hotelCheckIn" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "hotelCheckOut" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "hotelNotes" TEXT;
